https://dataexplorer.azure.com/clusters/help/databases/Samples?query=H4sIAAAAAAAAA5WRsWrDMBCG90De4fBkQw1xKtcOxVuHdimhaedwls6pqE4KklySkoevnGQKdOgixJ3uO/5PhiKwttsIHUQXJBr0uSJ2W2nGEMlru6vgBGFkRq9/aHqdrz1JHehdM20i8r4oHgHmMzPB8PAfGB7+gt3OzWcnoEMkqyDQLm3Qw5C/0U47C10HGeGYAabuJu2lD6vjuRzG5lJ+or1xRyYbX9S509eqUkINtWiUwIVAWdVtWz9UDake6yabz8448t9a0rMLFyA1w8NC1qoUKyFKsezvy9VyiemgVYstNYpkdgfZ2rveEE/XV+cZTVZMERi/qAwpEgWwI3fSjTbmBaQUtyJg8I6vvxPd1WzSsYdqwdAfJw8T0icn5CGmOfmJPv4CqV7NFNQBAAA=

let min_t = toscalar(demo_clustering1 | summarize min(PreciseTimeStamp));  
let max_t = toscalar(demo_clustering1 | summarize max(PreciseTimeStamp));  
demo_clustering1
| extend seg = iff(Region == "eau" and ScaleUnit == "su7" and DeploymentId == "b5d1d4df547d4a04ac15885617edba57"
and ServiceHost == "e7f60c5d-4944-42b3-922a-92e98a8e7dec", "Problem", "Normal")
| make-series num=count() on PreciseTimeStamp from min_t to max_t step 10m by seg
| render timechart